BB_CONF_FRAGMENT_SUMMARY = "rm_work default settings for meta-aesd"
BB_CONF_FRAGMENT_DESCRIPTION = "Turn on rm_work by default, but disable for aesd-assignments and core-image-aesd to support easier troubleshooting"
INHERIT += "rm_work"
RM_WORK_EXCLUDE += "aesd-assignments"
RM_WORK_EXCLUDE += "core-image-aesd"
